### ISSUE TITLE
Error Extract 

### ISSUE THREAD

**Issue by Supadon** [detroitbecometext/dbh-file-parser#2]
.\FileParser.exe extract -v --input "D:\SteamLibrary\steamapps\common\Detroit Become Human" --output "C:\Users\supad\Desktop\DTBH translate"

"BigFile_PC.d01": Done !
"BigFile_PC.d02": Section 1 of 8 -- 4% of section processed...
"BigFile_PC.d03": Section 1 of 42 -- 4% of section processed...
"BigFile_PC.d04": Section 1 of 1 -- 4% of section processed...
"BigFile_PC.d05": Section 1 of 1 -- 4% of section processed...
"BigFile_PC.d06": Section 1 of 25 -- 4% of section processed...
"BigFile_PC.d07": Section 1 of 9 -- 4% of section processed...
"BigFile_PC.d10": Section 1 of 3 -- 4% of section processed...
"BigFile_PC.d11": Section 1 of 84 -- 4% of section processed...
"BigFile_PC.d12": Section 1 of 95 -- 4% of section processed...
"BigFile_PC.d13": Section 1 of 70 -- 4% of section processed...
"BigFile_PC.d14": Section 1 of 104 -- 4% of section processed...
"BigFile_PC.d15": Section 1 of 82 -- 4% of section processed...
"BigFile_PC.d16": Section 1 of 95 -- 4% of section processed...
"BigFile_PC.d17": Section 1 of 91 -- 4% of section processed...
"BigFile_PC.d18": Section 1 of 45 -- 4% of section processed...
"BigFile_PC.d19": Section 1 of 52 -- 4% of section processed...
"BigFile_PC.d20": Section 1 of 63 -- 4% of section processed...
"BigFile_PC.d21": Section 1 of 114 -- 4% of section processed...
"BigFile_PC.d22": Section 1 of 85 -- 4% of section processed...
"BigFile_PC.d23": Section 1 of 18 -- 4% of section processed...
"BigFile_PC.d24": Section 1 of 1 -- 4% of section processed...
"BigFile_PC.d26": Section 1 of 1 -- 4% of section processed...
"BigFile_PC.dat": Section 1 of 6 -- 4% of section processed...
Unhandled exception: System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)v --input "D:\SteamLibrary\steamapps\common\Detroit Become
   at FileParser.Extraction.FileExtractor.FindValue(Byte[] buffer, Int32 currentKeyOffset, Byte[] currentKeyBytes, Byte[] nextKeyBytes, Boolean getUntilEndOfBuffer)
   at FileParser.Extraction.FileExtractor.ExtractAsync(ExtractParameters parameters, CancellationToken token)
   at FileParser.Extraction.ExtractionService.RunExtractionAsync(ExtractParameters parameters, CancellationToken token)
   at FileParser.Extraction.ExtractionService.ExtractAsync(ExtractParameters parameters, CancellationToken token)
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseHelp>b__13_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
   
   
   Could you give me some advice? What should I improve on?

**Comment by AreciboAntenna** [comment]
Same issue. You can try my extraction script in https://github.com/detroitbecometext/dbh-file-parser/pull/3

**Comment by Supadon** [comment]
> Same issue. You can try my extraction script in #3

Wow, your unpacker worked! I tried it, and I also found a Ukrainian tool that works too.{https://www.nexusmods.com/detroitbecomehuman/mods/40/?tab=files&jump_to_comment=136339710} But the problem is, the game doesn't have my country's font, so it doesn't display correctly. I'm currently trying to figure out how to mod the font into the game. If you know anything, please advise me.

Also, I'd like your permission to modify your unpacker further. I want to make it extract only the English text.

**Comment by AreciboAntenna** [comment]
Just do what you wish, type 2094 maybe the font you are looking for.
